### PR TITLE
#167164942 show user notification

### PR DESCRIPTION
**Pull request by benisi**
## Pivotal tracker story
[#167164942](https://www.pivotaltracker.com/story/show/167164954) 
#### What does this PR do?
 Add user show user notification functionality
#### Summary of Task
This PR adds the following to the project
 - add notification component
- add notification item component
- add previous and current test
- add socket.io to frontend
- add mark as read and mark all as read

#### How can this be tested?
```
# Clone this repository
$ git clone https://github.com/andela/dahlia-ah-frontend.git

# Navigate to the application folder
$ cd dahlia-ah-frontend

# Install dependencies
$ npm install

# start the server by typing
$ npm run dev

click on the notification icon, there will be a badge if you already have notification
```

### Screenshots 

notification

### CODE REVIEW

**Comment by benisi** [comment]
I have to work with Nero on the mobile view before I will be done

**Comment by Nkemjiks** [comment]
Is the data been fetched from the backend?

**Comment by benisi** [comment]
> Is the data been fetched from the backend?

Yes! i will add notification for user eden soon for test

**Review by Ukhu — APPROVED** [review]
LGTM

**Pull request merged**
