### PR TITLE
#168135723 Set up end-to-end test

### PR DESCRIPTION
**Pull request by OvieMudi**
#### What does this PR do?
- configure the project for end-to-end tests

#### Description of Task to be completed?
- Ensure the following dummy routes are tested

`Home:  /` 
`Dummy route:  /hello` 

#### How should this be manually tested?
To test manually on your local computer with `localhost`

```
# Clone this repository
$ git clone https://github.com/andela/dahlia-ah-frontend.git

# Navigate to the application folder
$ cd dahlia-ah-frontend

# Checkout the branch
$ git checkout chore/168135723/setup-end-to-end-testing
# Install dependencies
$ npm install

# Start the app in development mode
$ npm run dev

# Start Cypress e2e test
$ npm run e2e
```
- check the `.env.example` file on the environmental variables to provide

Note: See the screenshot below on how the  request/response should look
#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
[#168135723 ](https://www.pivotaltracker.com/story/show/168135723 )

#### Screenshots
Screenshot 2019-08-28 at 2 48 56 AM

### CODE REVIEW

**Comment by Nkemjiks** [comment]
Nice work @OvieMudi . Can we ignore the screenshots from cypress?

**Comment by OvieMudi** [comment]
> Nice work @OvieMudi . Can we ignore the screenshots from cypress?

Alright, I'll do that now

**Review by Nerocodes — APPROVED** [review]
LGTM

**Review by allebd — APPROVED** [review]
LGTM

**Review by Nkemjiks — APPROVED** [review]

**Pull request merged**
