### PR TITLE
#168197212 deploy application to Heroku

### PR DESCRIPTION
**Pull request by Rythae**
#### Pivotal Tracker Story

[#168197212](https://www.pivotaltracker.com/story/show/168197

#### What does this PR do?
 deploy the application to Heroku

#### Summary of Task
Screenshot 2019-08-29 at 7 35 19 PM

- add heroku-postbuild script
- configure app.json file for review app

 ### How can this be tested?
- git clone branch `chore/168197212/setup-heroku`
- install dependencies
- run npm install
- start dev server npm run start

### CODE REVIEW

**Comment by Nkemjiks** [comment]
Is this deployed to prod or staging?

**Comment by Rythae** [comment]
> Is this deployed to prod or staging?

To staging

**Comment by Nkemjiks** [comment]
> > Is this deployed to prod or staging?
> 
> To staging

Can you update the url to reflect that? The url from the screenshot doesn't prove that its for staging

**Comment by Rythae** [comment]
> > > Is this deployed to prod or staging?
> > 
> > 
> > To staging
> 
> Can you update the url to reflect that? The url from the screenshot doesn't prove that its for staging

Alright. I will do that now

**Review by Nkemjiks — APPROVED** [review]

**Pull request merged**
